### ISSUE TITLE
drupal console doesn't parse arguents language strings

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console-en#14]
it lacks the strings for arguments in several commands
not sure if it is something only happens to me :-/

![seleccion_501](https://cloud.githubusercontent.com/assets/423279/18788935/241ba65c-81a9-11e6-8b4e-87c4c8ab78bf.png)

![seleccion_502](https://cloud.githubusercontent.com/assets/423279/18789108/fb311e38-81a9-11e6-8a79-85955c33be1a.png)

**Comment by jmolivas** [comment]
This looks fixed, feel free to open if you consider needed.
